FROM node:22-alpine

WORKDIR /app

# 共通の依存関係をインストール
COPY package*.json ./
RUN npm install

# バックエンドの依存関係
COPY backend/package*.json ./backend/
RUN cd backend && npm install

# フロントエンドの依存関係
COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install

# すべてのソースコードをコピー
COPY . .

# 開発用のツールをインストール
RUN apk update && \
    apk add bash

CMD ["bash"]